## Statistics Related Functions

In [2]:
import numpy as np

In [3]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[85., 79., 68.],
       [17., 55., 51.],
       [ 3., 27., 11.]])

In [4]:
np.mean(k1)

np.float64(44.0)

In [5]:
#mean
k1

array([[85., 79., 68.],
       [17., 55., 51.],
       [ 3., 27., 11.]])

In [6]:
np.mean(k1)

np.float64(44.0)

In [7]:
# mean  of every column
k1.mean(axis = 0)

array([35.        , 53.66666667, 43.33333333])

In [8]:
# median
np.median(k1)

np.float64(51.0)

In [9]:
np.median(k1, axis = 1)

array([79., 51., 11.])

In [10]:
# Standard deviation
np.std(k1)

np.float64(28.751811537130433)

In [11]:
np.std(k1, axis = 0)

array([35.81433605, 21.2498366 , 23.89328125])

In [12]:
# variance
np.var(k1)

np.float64(826.6666666666666)

## Trigonometry Functions

In [13]:
np.sin(k1) # sin

array([[-0.17607562, -0.44411267, -0.89792768],
       [-0.96139749, -0.99975517,  0.67022918],
       [ 0.14112001,  0.95637593, -0.99999021]])

In [14]:
np.cos(k1)

array([[-0.98437664, -0.89597095,  0.44014302],
       [-0.27516334,  0.02212676,  0.7421542 ],
       [-0.9899925 , -0.29213881,  0.0044257 ]])

In [15]:
np.tan(k1)

array([[ 1.78870172e-01,  4.95677533e-01, -2.04008160e+00],
       [ 3.49391565e+00, -4.51830879e+01,  9.03086149e-01],
       [-1.42546543e-01, -3.27370380e+00, -2.25950846e+02]])

## Dot product
#### The numpy module of python provides a function to perform the dot product of two arrays

In [16]:
s2 = np.arange(12).reshape(3,4)
s3 = np.arange(12,24).reshape(4,3)

In [17]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [19]:
np.dot(s2,s3) # dot product of s2,s3

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

## Log and Exponents

In [20]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

### round / floor / ceil
### 1. round
#### The numpy.round() function rounds the elements of an array to the nearest integer or to the specific number of decimals.

In [21]:
# Round to the nearest integer
arr = np.array([1.2,2.7,3.5,4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 3. 4. 5.]


In [23]:
# Round to two decimals
arr = np.array([1.2344, 2.567, 3.891])
rounded_arr = np.round(arr,decimals=2)
print(rounded_arr)

[1.23 2.57 3.89]


In [24]:
# Randomly
np.round(np.random.random((2,3))*100)

array([[39., 49., 69.],
       [42., 67., 50.]])

### 2. floor
#### The numpy.floor() function returns the largest integer less than or equal to each element of an array.

In [25]:
# Floor operation
arr = np.array([1.2,2.7,3.5,4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [27]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer

array([[30., 20., 43.],
       [80., 36., 87.]])

### 3. ceil
#### The numpy.ceil() function returns the smallest integer greater than or equal to each element of an array

In [28]:
arr = np.array([1.2,2.7,3.5,4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [29]:
np.ceil(np.random.random((2,3))*100)

array([[79., 52., 17.],
       [55., 17., 62.]])