## Linspace

#### It is also called as linearly space , Linearly separable,in a given range at equal distance it creates points

In [2]:
import numpy as np

In [3]:
np.linspace(-10,10,10) # here: lower range, upper range, number of items to generate

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [4]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

## Identity

#### indentity matrix is that diagonal items will be ones and everything will be zeros

In [5]:
# creating the indentity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Array Attributes

In [7]:
a1 = np.arange(10) #1d
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a2 = np.arange(12,dtype=float).reshape(3,4) # Mtrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [9]:
a3 = np.arange(8).reshape(2,2,2) #3D --> Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## NDIM
#### To findout given arrays number of dimensions

In [10]:
a1.ndim

1

In [11]:
a2.ndim

2

In [12]:
a3.ndim

3

## Shape
#### given each item consist of no. of ows and np.of columns

In [13]:
a1.shape #1D array has 10 items

(10,)

In [14]:
a2.shape # 3 rows and 4 columns

(3, 4)

In [15]:
a3.shape # first, 2 says it consists of 2D arrays. 2,2 gives no. of ows and columns

(2, 2, 2)

## Size
#### gives number of items

In [16]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
a3.size # it has 8 items . like shape :2,2,2 = 8 

8

In [18]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
a2.size

12

## Item size
#### Memory occupied by the item

In [20]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a1.itemsize #bytes

8

In [22]:
a2.itemsize #integer 64 gives = 8 bytes 

8

In [23]:
a3.itemsize # integer 32 gives = 4 bytes

8

## Dtype
#### gives data type of the item

In [25]:
print(a1.dtype) 
print(a2.dtype) 
print(a3.dtype) 

int64
float64
int64
