In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys
sys.version


'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

# CREATING ARRAYS

In [4]:
my_list = [0,1,2,3,4,5]
my_list


[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20,10)

array([], dtype=int64)

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [21]:
np.arange(30,20) # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [22]:
ar = np.arange(-30,20)
ar


array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [23]:
np.arange(10,10)

array([], dtype=int64)

In [24]:
np.arange()

TypeError: arange() requires stop to be specified.

In [25]:
np.arange(10,30,5) # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [26]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [27]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [28]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

In [29]:
np.zeros(5, dtype = int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [30]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [31]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [33]:
zero = np.zeros([2,2])
print(zero)
print('####')
print(type(zero))


[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [34]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.zeros((10,30,))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [38]:
np.zeros((5,10)) # bydefaul large -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunning



[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
print(np.zeros(n,dtype = int)) # hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [41]:
n

(6, 7)

In [42]:
n1

(6, 8)

In [43]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [44]:
np.ones(3)

array([1., 1., 1.])

In [45]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [46]:
np.ones(4)

array([1., 1., 1., 1.])

In [47]:
n

(6, 7)

In [48]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [49]:
np.ones((5,4),dtype = int) # by default 5 - rows and 4 - colums

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [50]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [51]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [52]:
np.ones(2)

array([1., 1.])

In [53]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.ones((6,10),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [55]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [56]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [57]:
range(5)

range(0, 5)

In [59]:
r = range(5)
r


range(0, 5)

In [60]:
for i in r:
     print(i)


0
1
2
3
4


In [61]:
list(range(5))

[0, 1, 2, 3, 4]

In [62]:
range(1,10)

range(1, 10)

In [63]:
list(range(1,10,3))

[1, 4, 7]

In [65]:
y = list(range(12))
y


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [66]:
rand(3,2)

NameError: name 'rand' is not defined

In [67]:
rand(3,2)
random.rand(3,2)


NameError: name 'rand' is not defined

In [68]:
np.random.rand(5)

array([0.29983154, 0.86484121, 0.75343236, 0.51896986, 0.73190448])

In [69]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [71]:
np.random.rand(2,4)

array([[0.69761192, 0.23154032, 0.12308743, 0.93784098],
       [0.7644467 , 0.44304263, 0.95647829, 0.7706918 ]])

In [72]:
np.random.randint(2,4)

3

In [74]:
np.random.randint(2,20) # 2 nd argument is exclusive

14

In [78]:
np.random.randint(0,1)

0

In [80]:
np.random.randint(10,20,5)

array([17, 18, 18, 14, 13], dtype=int32)

In [81]:
np.random.randint(1,6,4)

array([2, 3, 2, 4], dtype=int32)

In [82]:
np.random.rand(3)

array([0.84511922, 0.50292731, 0.42944939])

In [83]:
np.random.randint(1)

0

In [84]:
np.random.randint(30,20,10)

ValueError: low >= high

In [85]:
np.random.randint(-30,20,10)

array([ 18, -20, -17,   8, -16,  15, -21, -29,   6,  11], dtype=int32)

In [86]:
np.random.randint(20,30,10)

array([21, 24, 26, 24, 28, 23, 25, 25, 28, 26], dtype=int32)

In [87]:
np.random.randint(5,9) #Get the vlue <=1 & >=5

5

In [88]:
np.random.randint(10,21,3)

array([13, 17, 19], dtype=int32)

In [89]:
np.random.randint(1,12,10)

array([ 1,  8,  1,  7,  6,  5, 11,  4, 11,  9], dtype=int32)

In [90]:
np.random.randint(10,40,(10,10)) #generre the elements 10 -30 with 4*4 mtri

array([[14, 34, 17, 25, 15, 14, 24, 36, 39, 23],
       [12, 18, 22, 32, 20, 36, 17, 29, 18, 14],
       [23, 12, 12, 13, 20, 25, 34, 25, 23, 10],
       [14, 32, 20, 20, 11, 36, 25, 37, 39, 23],
       [30, 30, 34, 16, 31, 34, 10, 19, 37, 28],
       [37, 15, 36, 23, 26, 29, 24, 30, 39, 16],
       [38, 20, 18, 13, 13, 37, 26, 36, 21, 30],
       [33, 15, 30, 21, 22, 12, 25, 35, 17, 13],
       [34, 22, 21, 16, 14, 33, 36, 17, 13, 21],
       [18, 31, 13, 34, 16, 15, 12, 14, 27, 12]], dtype=int32)

In [91]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[61, 29, 27, 88, 93, 61, 59, 75, 86, 82, 37, 61],
       [73,  2, 16, 19, 73, 27, 55, 30, 56, 51, 32,  4],
       [16, 37, 40,  5,  7,  3, 19, 19,  2, 58, 54, 75],
       [11, 40, 25, 38, 48, 47, 98, 32, 76, 42,  7, 28],
       [72, 47, 33, 32, 87, 48, 55, 47, 41, 53, 72, 51],
       [12, 24, 24, 85, 23, 28,  1, 55, 91, 67, 38, 52],
       [80, 89, 21, 22, 44, 21,  8, 69, 96,  1, 36, 43],
       [56, 17, 82, 74, 56, 47, 33, 95, 70,  8, 36, 84],
       [ 4, 49, 77, 58,  2, 62, 58, 33, 21, 75,  8, 66],
       [ 5,  9, 65, 25, 61, 20, 18, 38, 31, 89, 31, 97],
       [76,  2, 88, 28, 27, 20, 11, 89,  6, 52, 71, 13],
       [72, 27, 27, 70, 47, 55, 52, 34, 21, 33, 44, 85]], dtype=int32)

In [93]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [96]:
b = np.random.randint(10,20,(5,4))
b


array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [97]:
type(b)

numpy.ndarray

In [98]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [99]:
b[:]

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [100]:
b[1:3]

array([[17, 16, 15, 19],
       [10, 12, 11, 14]], dtype=int32)

In [101]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [102]:
b[1,2]

np.int32(15)

In [103]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [104]:
b[1,3]

np.int32(19)

In [105]:
b[1,-1]

np.int32(19)

In [106]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [107]:
b[2:3]

array([[10, 12, 11, 14]], dtype=int32)

In [108]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [109]:
b[0:-2]

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14]], dtype=int32)

In [110]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [111]:
b[0,2]

np.int32(14)

In [112]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [113]:
b[-5,-3]

np.int32(18)

In [114]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [115]:
b[-4,2]

np.int32(15)

In [117]:
np.random.randint(10,20,(4,4))

array([[19, 11, 19, 11],
       [15, 14, 14, 17],
       [17, 15, 13, 14],
       [16, 12, 18, 19]], dtype=int32)

In [118]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [119]:
b[-4,-2]

np.int32(15)

In [120]:
b

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

In [121]:
b[-4:2]

array([[17, 16, 15, 19]], dtype=int32)

In [122]:
b[:]

array([[19, 18, 14, 11],
       [17, 16, 15, 19],
       [10, 12, 11, 14],
       [15, 12, 12, 19],
       [16, 13, 11, 10]], dtype=int32)

# Operations

In [123]:
a = np.random.randint(10,20,10)
a


array([19, 10, 15, 18, 17, 17, 18, 19, 13, 17], dtype=int32)

In [124]:
id(a)

1958005348304

In [125]:
arr

array([0, 1, 2, 3, 4, 5])

In [126]:
arr2 = np.random.randint(0,100,(10,10))

In [127]:
arr2

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [128]:
arr

array([0, 1, 2, 3, 4, 5])

In [129]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [130]:
arr

array([0, 1, 2, 3, 4, 5])

In [131]:
arr[:4]

array([0, 1, 2, 3])

In [132]:
arr2[:]

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [133]:
arr2[0:5]

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42]], dtype=int32)

In [134]:
arr2

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [135]:
arr2[1,4]

np.int32(14)

In [136]:
arr2

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [137]:
arr2[-5,5]

np.int32(62)

In [138]:
arr2[-5,-5]

np.int32(62)

In [139]:
arr2

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [140]:
arr2[-5,-5]

np.int32(62)

In [141]:
arr2

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [142]:
arr2[-1,-2]

np.int32(71)

In [143]:
arr2

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [144]:
arr2[::-1]

array([[25,  9, 86, 34, 79, 84, 12, 71, 71, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [98, 73,  6, 58, 69, 43,  8, 72, 48, 37]], dtype=int32)

In [145]:
arr2

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [146]:
arr2[::-2]

array([[25,  9, 86, 34, 79, 84, 12, 71, 71, 30],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92]], dtype=int32)

In [147]:
arr2

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [148]:
arr2[::-3]

array([[25,  9, 86, 34, 79, 84, 12, 71, 71, 30],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [98, 73,  6, 58, 69, 43,  8, 72, 48, 37]], dtype=int32)

In [149]:
arr2

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43],
       [30, 45, 82, 91, 28, 54, 70, 59, 27, 30],
       [ 9, 40, 80, 19, 63, 91, 53, 64, 25, 27],
       [25,  9, 86, 34, 79, 84, 12, 71, 71, 30]], dtype=int32)

In [150]:
arr2[:-3]

array([[98, 73,  6, 58, 69, 43,  8, 72, 48, 37],
       [78,  7, 90, 87, 14, 93, 99, 79,  9, 92],
       [80, 44, 33, 12, 94, 58, 69, 15, 10, 53],
       [56, 89, 31,  3, 79, 31, 54, 56, 58, 87],
       [92, 33, 45, 11, 67, 96, 40,  1,  3, 42],
       [12, 50, 59, 45, 17, 62, 40, 13, 84, 29],
       [89, 53, 64, 71, 54, 28, 71, 70, 79, 43]], dtype=int32)

In [151]:
arr

array([0, 1, 2, 3, 4, 5])

In [152]:
arr.max()

np.int64(5)

In [153]:
arr.min()

np.int64(0)

In [154]:
arr

array([0, 1, 2, 3, 4, 5])

In [156]:
arr.mean()

np.float64(2.5)

In [157]:
arr

array([0, 1, 2, 3, 4, 5])

In [158]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [159]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)