In [3]:
import numpy as np

In [4]:
np.__version__

'2.3.5'

In [5]:
np. 

SyntaxError: invalid syntax (2652304867.py, line 1)

In [ ]:
my_list = [0,1,2,3,4,5]
my_list

In [ ]:
type(my_list)

In [ ]:
arr = np.array(my_list) 
arr ##converting list to array

In [ ]:
type(arr)

In [ ]:
arr

In [ ]:
np.arange(10)

In [ ]:
np.arange(10,20)

In [ ]:
np.arange(10,20,3)

In [ ]:
np.zeros(5)

In [ ]:
np.zeros(5, dtype=int)

In [ ]:
np.zeros((2,2)) #2d array 

In [ ]:
np.zeros((2,2), dtype=int)

In [ ]:
np.zeros((5,10), dtype=int)

In [ ]:
np.ones(10)

In [ ]:
np.ones(10, dtype=int)

In [ ]:
np.ones((3,3),dtype=int) #3x3 matrix

In [ ]:
np.twos(3) #there is no attributes can check by np.tab

In [ ]:
rand(4)

In [ ]:
random.rand(4)

In [ ]:
np.random.rand(4)

In [ ]:
np.random.rand(4) # every time it gives random numbers

In [ ]:
np.random.rand(2,2)

In [ ]:
np.random.randint(3) #gives int values -- low to high , low is inclusive , high is exclusive 

In [ ]:
np.random.randint(10,15) #it gives values b/w 10 to 15 but 15 is exclusive

In [ ]:
np.random.randint(1,5,3)

In [ ]:
np.random.randint(1,5,4) 

In [ ]:
np.random.randint(1,5,2) 

In [ ]:
np.random.randint(5, 2, 3) 

In [ ]:
np.random.randint(-5, 2, 3)

In [ ]:
np.random.randint(10,40,(10,10)) #generate the element 10 - 40 with 4*4 matrix

In [ ]:
ri = np.random.randint(10,40,(10,10))
ri

In [ ]:
len(ri) # it will print by default 10 rows

In [ ]:
ri = np.random.randint(10,40,(3,5))
ri

In [ ]:
len(ri)

In [ ]:
ri.shape # it will give rows and columns shape of the matrix

In [ ]:
id(ri) # memory location

In [ ]:
ri

# slicing in numpy

In [ ]:
ri[:] # it prints all 

In [ ]:
ri[1] # prints 1st row

In [ ]:
ri[0:3] #prints 0-2 rows

In [ ]:
ri_1 = np.random.randint(10,40,(10,10))
ri_1

In [ ]:
ri_1.shape

In [ ]:
ri_1 = np.random.randint(10,40,(10,10))
print(ri_1) #dtype = int32 will dissapear if we use print func

In [ ]:
ri_1

In [ ]:
ri_1[3:8] #prints rows

In [ ]:
ri_1[3,8] # its give the value present  in the 3rd row 8th column

In [ ]:
print(ri_1[3,8])

In [ ]:
ri_1

In [ ]:
ri_1[-5] #count from downwards -1,-2..

In [ ]:
print(ri_1[-5, -3])

In [ ]:
ri_1[::3] #prints the rows by skipping the rows prints 0th row and 3rd row

In [ ]:
ri_1

In [ ]:
ri_1[::-1] #print the whole array reverse

In [ ]:
ri_1[::-5]

In [ ]:
ri_1

In [ ]:
ri_1[::-5] #prints backwards

In [ ]:
ri_1

In [ ]:
ri_1[2] # gives 2nd row

In [ ]:
print(ri_1[2]) # 2nd row
print(ri_1[:,2]) #2nd column

In [ ]:
ri_1

In [ ]:
ri_1[:, 8]

In [ ]:
ri_1[:, -8] #8th column in backward

In [ ]:
ri_1

In [ ]:
ri_1[2:6, 5:8]

In [ ]:
ri_1[0:3, 0:3]

In [ ]:
np.arange(1,13) #gives values arrange from 1 to 13

In [ ]:
np.arange(1,13).reshape(3,4) # gives values b/w 1 to 13 arranged in 3 rows 4 columns

In [ ]:
np.arange(1,13).reshape(5,4) #we need more values

In [ ]:
np.arange(1,13).reshape(4,3)

In [ ]:
np.arange(1,13).reshape(2,6)

In [6]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [8]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

# Numpy Masking or Filter

In [9]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [10]:
id(mat)

2441669294864

In [11]:
mat.shape

(10, 10)

In [12]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
mat < 50 # we need vales less than 50, but here its checking the condition giving the values in true or false

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [14]:
mat[mat < 50] #this is known as filter

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
mat[mat <= 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
mat[mat == 50]

array([50])

In [17]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
 np.

SyntaxError: invalid syntax (166395737.py, line 1)

# Array Creation Functions

In [ ]:
import numpy as np

In [ ]:
# Create an array from a list
a = np.array([1,2,3])
print("Array a:",a)

In [ ]:
#Create an array with evenly spaced values
b = np.arange(0,10,2) # Values from 0 to 10 with step 2
print("Array b:",b)

In [ ]:
#Create an array filled with zeros
d = np.zeros((2,3),) # 2 x 3 array of zeros
print("Array d:\n",d)

In [ ]:
#Create an array filled with zeros
d = np.zeros((2,3),dtype=int) # 2x3 array of zeros
print("Array d:\n",d)

In [ ]:
#Create an array filled with ones
e = np.ones((3,2)) 
print("Array e:\n",e)

In [ ]:
# Create an identity matrix
f = np.eye(4) # 4x4 identity matrix all diagonals will be 1
print("Identity matrix f:\n",f)

In [ ]:
# Create an identity matrix
f = np.identity(4) # 4x4 identity matrix all diagonals will be 1
print("Identity matrix f:\n",f)

# 2. Array Manipulation Functions

In [ ]:
# Reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3)) # Reshape to 1x3
print("Reshape array:",reshaped)

In [ ]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1)) #Reshape to 3x1
print("Reshaped array:",reshaped)

In [ ]:
# Flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8]])
flattened = np.ravel(f1) #flatten to 1D array
print("Flattened array:",flattened)

In [ ]:
# Transposed an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) # Transpose the array
print("Transposed Array:\n", transposed) # it will change rows into columns and columns into rows

In [ ]:
# stack arrays vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2]) # stack a and b vertically
print("Stacked arrays:\n",stacked)

In [ ]:
# stack arrays horizontally
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2]) # stack a and b horizontally
print("Stacked arrays:\n",stacked)

# 3.Mathematical Functions

In [ ]:
# Add two arrays
g = np.array([1,2,3,4])
added = np.add(g,2) # Add 2 to each ele
print ("Added 2 to g:",added)              

In [ ]:
#Square each ele
squared = np.power(g,2) #square each ele
print("Squared g:",squared)

In [ ]:
#square root of each ele
sqrt_val = np.sqrt(g) # square root of each ele
print("Square root of g:",sqrt_val)

In [ ]:
print(a1)
print(g)

In [ ]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g) # Dot product of a and g
print("Dot product of a and g:",dot_product) # dot product doesnot work with diff shape it must be same shape to work

In [ ]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,g) # Dot product of a1 and g
print("Dot product of a1 and g:",dot_product)

In [ ]:
print(a)
print(a1)

In [ ]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a) # Dot product of a1 and a
print("Dot product of a1 and a:",dot_product)

# 4. Statistical Functions

In [ ]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s",mean) # sum of numbers / total numbers

In [ ]:
# Variance of an array
var = np.var(s) # (1-2.5)^2 + (2-2.5)^2 + (3-2.5)^2 + (4-2.5)^2 / 4
print("variance of s:",var)

In [ ]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:",std_dev) # root of variance will give std val in float

In [ ]:
# Minimum ele of an array
minimum = np.min(s)
print("Min of s:",minimum)

In [ ]:
# maximum ele of an array
maximum = np.max(s)
print("Min of s:",maximum)

# 5. Random Sampling Functions

In [21]:
random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random values:",random_vals)

Random values: [0.66511552 0.80120462 0.74704569]


In [25]:
# set seed for reproducibility
np.random.seed(0)
# Generate random values between 0 and 1
random_vals = np.random.rand(3) # Array of 3 random values b/w 0 and 1
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [30]:
rand_ints = np.random.randint(0,10,size = 5) #Generates random int b/w 0 to 10
print("Random integers:",rand_ints)


Random integers: [9 3 5 2 4]


In [31]:
# set seed for reproducibility
np.random.seed(0)

rand_ints = np.random.randint(0,10,size = 5) #Generates random int b/w 0 to 10
print("Random integers:",rand_ints)

Random integers: [5 0 3 3 7]


# 6.Boolean and Logical functions

In [32]:
#check if all elements are true
#all
logical_test = np.array([True,False,True])
all_true = np.all(logical_test) # check if all are true
print("All elements True:",all_true)





All elements True: False


In [33]:
#Check if all elements are true
logical_test = np.array([False,False,False])
all_true = np.all(logical_test) # check if all are true
print("All elements True:",all_true)


All elements True: False


In [35]:
#check if any element are true
#any
any_true = np.any(logical_test) #check if any are true
print("Any elements True:",any_true)


Any elements True: False


# 7. Set Operations

In [37]:
#Intersection of two arrays
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [3 4]


In [38]:
#Union of two arrays
union = np.union1d(set_a,set_b)
print("Union of a and b:",union)

Union of a and b: [1 2 3 4 5 6]


# 8.Array Attribute Functions

In [39]:
#Array attributes
a = np.array([1,2,3])
shape = a.shape #shape of the array
size = a.size # number of ele
dimensions = a.ndim # num of dimensions
dtype = a.dtype #data type of te array

print("Sahpe of a:",shape)
print("Size of a:",size)
print("Number of dimensions of a:",dimensions)
print("Data type of a:",dtype)


Sahpe of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# 9. Other Functions

In [40]:
# create a copy of an array
a = np.array([1,2,3])
copied_array = np.copy(a) #create a copy of array a
print("Copied array:",copied_array)


Copied array: [1 2 3]


In [41]:
#Size in bytes of an array
array_size_in_bytes = a.nbytes #Size in bytes
print("Size of a in  bytes:",array_size_in_bytes)

Size of a in  bytes: 24


In [42]:
#check if two arrays share memory
shared = np.shares_memory(a,copied_array) #check if arrays share memory
print("Do a and copied_array share memory?",shared)

Do a and copied_array share memory? False
