# Creating Numpy Array

In [1]:
import numpy as np

In [2]:
np.array([2,4,56,422,32,1]) # 1D array

array([  2,   4,  56, 422,  32,   1])

In [3]:
a = np.array([2,4,56,422,32,1]) # vector

In [4]:
print(a)

[  2   4  56 422  32   1]


In [5]:
type(a)

numpy.ndarray

In [8]:
# 2D array (Matrix)
new = np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [9]:
# 3 D ---- # Tensor
np.array ([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])


array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

## DTYPE

In [10]:
np.array([11,23,44],dtype=float)

array([11., 23., 44.])

In [11]:
np.array([11,23,44],dtype=bool) # Here True bcz, python treats Non -zero

array([ True,  True,  True])

In [12]:
np.array([11,23,44], dtype = complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

## Arange

#### arange can be called with a varying number of positional arguments


In [13]:
np.arange(1,25) # 1- included, 25 - last one got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
np.arange(1,25,2) #strides ---> Alternate numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

## Reshape

#### Both of number products should be equal to number of items present inside the array


In [15]:
np.arange(1,11).reshape(5,2) # converted 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
np.arange(1,11).reshape(2,5) # conerted 2 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.arange(1,13).reshape(3,4) # converted 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Ones and Zeris

#### you can initialize the values and create values. ex: in deep learning weight shape


In [19]:
# np.ones and np.zeros
np.ones((3,4)) # we have to mention inside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# Another type ---> random()
np.random.random((4,3))


array([[0.71968843, 0.75549061, 0.9750725 ],
       [0.19403311, 0.99929268, 0.87144554],
       [0.81144625, 0.24493325, 0.13629841],
       [0.69870053, 0.94712333, 0.2772987 ]])