In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [4]:
my_list = [0,1,2,3,4,5]
my_list


[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr


array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5, dtype = int) # 1d array

array([0, 0, 0, 0, 0])

In [15]:
np.zeros((2,2)) # 2d array

array([[0., 0.],
       [0., 0.]])

In [16]:
np.zeros((5,19),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [20]:
rand(4)

NameError: name 'rand' is not defined

In [21]:
random.rand(4)

NameError: name 'random' is not defined

In [22]:
np.random.rand(4)

array([0.84232683, 0.78478871, 0.49030617, 0.41081715])

In [23]:
np.random.rand(2,2)

array([[0.1731857 , 0.44691892],
       [0.79265906, 0.72783883]])

In [24]:
np.random.rand(3)

array([0.45925248, 0.67934674, 0.46571274])

In [25]:
np.random.randint(10,15)

13