# Changing Data Type

In [2]:
import numpy as np

In [4]:
#astype
x = np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [5]:
x.astype(int)

array([33, 22,  2])

## Array Operations

In [6]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)


In [7]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Scalar Operations
#### Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication on each element of a Numpy array.


In [9]:
# rithmetic
z1 + 2


array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [10]:
# Subtraction
z1 - 2


array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [11]:
# Multiplication
z1 * 2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [12]:
# power
z1 ** 2


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [13]:
# modulo
z1 % 2


array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

## Relational Operators
#### The relational operators are also known as comparision operators, their main function is to return either true or false based on the value of operands


In [14]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
z2 > 2 # if 2 greater than everything gives true

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

## Vector Operation
#### we can apply on both numpy array


In [17]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
# Arithmetic 
z1 + z2 # both numpy array shape is same, we can add item wise


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [20]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [21]:
z1 / z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

## Array Functions

In [23]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[25.,  2., 95.],
       [58., 18., 61.],
       [86., 44., 62.]])

In [24]:
# Max
np.max(k1)


np.float64(95.0)

In [25]:
# Min
np.min(k1)


np.float64(2.0)

In [26]:
# sum
np.sum(k1)


np.float64(451.0)

In [27]:
# prod -----> Multiplication
np.prod(k1)


np.float64(70968685392000.0)

## In Numpy
#### 0 = column, 1 = row


In [28]:
# if we want maximum of every row
np.max(k1, axis = 1)


array([95., 61., 86.])

In [29]:
# maximum of every column
np.max(k1, axis = 0)


array([86., 44., 95.])

In [30]:
# product of evry column
np.prod(k1, axis = 0)


array([124700.,   1584., 359290.])