## Indexing And Slicing

In [1]:
import numpy as np

In [2]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [3]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## Indexing on 1D array

In [6]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# fetching last item
p1[-1]

np.int64(9)

In [8]:
# fetching first item
p1[0]

np.int64(0)

## Indexing on 2D array

In [9]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# fetching desired element : 6
p2[1,2] # here 1 = row(second) , 2=column(third) because it starts from zero

np.int64(6)

In [11]:
# fetching desired element : 11
p2[2,3] # row = 2, column = 3

np.int64(11)

In [12]:
# fetching desired element : 4
p2[1,0] # row = 1, column = 0


np.int64(4)

## Indexing on 3D (Tensors)

In [13]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# fetching desired element : 5
p3[1,0,1] #EXPLANATION :Here 3D is consists of 2 ,2D array , so Firstly we take 1 because our desired is 
#5 is in second matrix which is 1 .and 1 row so 0 and second column so 1 

np.int64(5)

In [16]:
# fetching desired element : 2
p3[0,1,0]
# :Here firstly we take 0 because our desired is 2, is in first matrix which is 0 . 
#and 2 row so 1 and first column so 0

np.int64(2)

In [17]:
#  fetching desired element : 0
p3[0,0,0]
# Here first we take 0 because our desired is 0, is in first matrix which is 0 . and 1 row so 0 and 
# first column so 0 

np.int64(0)

In [18]:
#  fetching desired element : 6
p3[1,1,0]
#  Here first we take because our desired is 6, is in second matrix which is 1 . 
# and second row so 1 and first column so 0

np.int64(6)

## Slicing
##### Fetching Multiple items

### Slicing on 1D

In [19]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#  fetching desired element : 2,3,4
p1[2:5]
# Here First we take , whatever we need first item ,2 and up last(4) + 1 which 5 
#.because last element is not included

array([2, 3, 4])

In [21]:
#  Alternate (same as python) 
p1[2:5:2]

array([2, 4])

### Slicing on 2D

In [22]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
# fetching total first row
p2[0,:]
# Here 0 represents first row and (:) represnts Total column

array([0, 1, 2, 3])

In [24]:
# fetching total third column
p2[:,2]
# Here we want all rows so (:) , and we want 3rd column so 2 

array([ 2,  6, 10])

In [25]:
# fetch 5,6 and 9,10
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
p2[1:3] # for rows

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
p2[1:3 , 1:3] # for columns
# Here first [1:3] we slice 2 second row is to third row is not existed which is 2 
# and Secondly , we take [1:3] which is same as first:we slice 2 second row is to third row is not 
# included which is 3

array([[ 5,  6],
       [ 9, 10]])

In [28]:
# fetch 0,3 and 8, 11
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
p2[::2, ::3]
# Here we take (:) because we want all rows , second(:2) for alternate value, 
# and (:) for all columns and (:3) jump for two steps

array([[ 0,  3],
       [ 8, 11]])

In [30]:
# fetch 1,3 and 9,11
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
p2[::2] # for rows

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [32]:
p2[::2 , 1::2] # columns
# Here we take (:) because we want all rows , second(:2) for alternate value, 
# and (1) for we want from second column and (:2) jump for two steps and ignore middle one 

array([[ 1,  3],
       [ 9, 11]])

In [33]:
# fetch only 4,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
p2[1] # first rows

array([4, 5, 6, 7])

In [35]:
p2[1,::3] # second columns
# Here we take (1) because we want second row , second(:) for total column, 
# (:3) jump for two steps and ignore middle ones

array([4, 7])

In [36]:
# fetch 1,2,3 and 5,6,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
p2[0:2] # first fetched rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
p2[0:2 , 1:] # for column

array([[1, 2, 3],
       [5, 6, 7]])

In [39]:
# fetch 1,3 and 5,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
p2[0:2] # for rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
p2[0:2 , 1::2]
#  0:2 selects the rows from index 0 (inclusive) to index 2 (exclusive), which 
# means it will select the first and second rows of the array. , is used to separate row and column 
# selections. 1::2 selects the columns starting from index 1 and selects every second column. So 
# it will select the second and fourth columns of the array. 

array([[1, 3],
       [5, 7]])

### Slicing in 3D

In [42]:
p3 = np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
# fetch second matrix
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [45]:
# fetch first and last
p3[::2]
#  Along the first axis, (::2) selects every second element. This means it will 
# select the subarrays at indices 0 and 2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [46]:
# Fetch 1 2d array's 2 row ---> 3,4,5 
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
p3[0] # first numpy array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
p3[0,1,:]
# 0 represnts first matrix , 1 represents second row , (:) means total 

array([3, 4, 5])

In [50]:
# Fetch 2 numpy array ,middle column ---> 10,13,16
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
p3[1] # middle Array

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [52]:
p3[1,:,1]
# 1 respresnts middle column , (:) all columns , 1 represnts middle column

array([10, 13, 16])

In [53]:
#  Fetch 3 array--->22,23,25,26
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
p3[2] # last row

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [55]:
p3[2,1:] # last two rows

array([[21, 22, 23],
       [24, 25, 26]])

In [56]:
p3[2,1:,1:] # last two columns
#Here we go through 3 stages , where 2 for last array , and (1:) from second 
# row to total rows , and (1:) is for second column to total columns

array([[22, 23],
       [25, 26]])

In [57]:
# fetch 0, 2, 8, 20
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
p3[0::2] # for arrays

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [59]:
p3[0::2, 0] # for rows

array([[ 0,  1,  2],
       [18, 19, 20]])

In [61]:
p3[0::2, 0, ::2] # for columns
# Here we take (0::2) first adn last column , so we did jump using this, and we 
# took (0) for first row , and we (::2) ignored middle column

array([[ 0,  2],
       [18, 20]])